import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams, useLocation } from 'react-router-dom';
import { FaArrowLeft, FaArrowRight, FaHeart, FaPlus, FaSearch, FaTimes, FaSignOutAlt, FaCamera, FaDownload, FaShareAlt } from 'react-icons/fa';
import { collections, disciplines } from './data';
import './studio.css';

function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function normalize(text) { return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }

function Image({ src, alt, ...props }) {
  const [failed, setFailed] = useState(false);
  if (failed) return <div className="image-fallback" role="img" aria-label={alt}><FaCamera /><span>Imagen no disponible</span></div>;
  return <img src={src} alt={alt} loading="lazy" onError={() => setFailed(true)} {...props} />;
}

export function Welcome() {
  return <main className="studio-welcome"><div className="welcome-photo"><Image src={collections[0].cover} alt="Amanecer sobre las montañas" /></div><div className="welcome-copy"><Link className="wordmark" to="/">nexo<span>estudio</span></Link><span className="kicker">FOTOGRAFÍA & ARTE VISUAL</span><h1>Una mirada.<br />Un mundo propio.</h1><p>Un espacio para construir tu archivo, descubrir otras miradas y darle lugar a tu trabajo.</p><Link className="solid-button" to="/register">Crear mi espacio <FaArrowRight /></Link><Link className="text-link" to="/login">Ya tengo una cuenta</Link><small>Acceso de prueba · las cuentas todavía no se verifican.</small></div></main>;
}

function Card({ album, saved, onSave }) {
  return <article className="work-card"><Link className="work-image" to={`/album/${album.id}`}><Image src={album.cover} alt={album.title} /></Link><div className="work-meta"><span>{album.discipline}</span><button className={`save-button ${saved ? 'is-saved' : ''}`} onClick={() => onSave(album.id)} aria-label={saved ? `Quitar ${album.title} de guardados` : `Guardar ${album.title}`} aria-pressed={saved}><FaHeart /></button></div><Link to={`/album/${album.id}`}><h2>{album.title}</h2></Link><Link className="author-link" to={`/autor/${encodeURIComponent(album.author)}`}>{album.author} <span>↗</span></Link></article>;
}

function CollectionPage({ albums, saved, onSave, mode }) {
  const [params, setParams] = useSearchParams();
  const [sort, setSort] = useState('recent');
  const query = params.get('q') || '';
  const category = params.get('disciplina') || 'Todas';
  const tag = params.get('etiqueta');
  const list = albums.filter(a => (mode !== 'mine' || a.local) && (mode !== 'saved' || saved.includes(a.id)) && (mode === 'mine' || mode === 'saved' || a.visibility !== 'private')).filter(a => normalize([a.title, a.author, a.location, ...a.tags].join(' ')).includes(normalize(query)) && (category === 'Todas' || a.discipline === category) && (!tag || a.tags.includes(tag))).sort((a,b) => sort === 'title' ? a.title.localeCompare(b.title, 'es') : b.date.localeCompare(a.date));
  function filter(key, value) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next, { replace: true }); }
  return <><section className="page-intro"><span className="kicker">{mode === 'mine' ? 'TU ARCHIVO' : mode === 'saved' ? 'TU SELECCIÓN' : 'EL ARCHIVO ABIERTO'}</span><h1>{mode === 'mine' ? 'Tu trabajo, en series.' : mode === 'saved' ? 'Miradas que guardaste.' : 'Lo que merece una segunda mirada.'}</h1><p>{mode === 'mine' ? 'Organizá tus fotos y elegí qué compartir.' : mode === 'saved' ? 'Un lugar para volver a lo que te inspira.' : 'Series de fotografía y arte visual. Sin apuro, imagen por imagen.'}</p></section><div className="collection-tools"><div className="category-tabs" aria-label="Disciplinas">{disciplines.map(d => <button key={d} className={category === d ? 'selected' : ''} onClick={() => filter('disciplina', d === 'Todas' ? '' : d)} aria-pressed={category === d}>{d}</button>)}</div><select value={sort} onChange={e => setSort(e.target.value)} aria-label="Ordenar series"><option value="recent">Más recientes</option><option value="title">Título A–Z</option></select></div><label className="collection-search"><FaSearch /><input value={query} onChange={e => filter('q', e.target.value)} placeholder="Buscar título, autor, lugar o etiqueta" aria-label="Buscar series" /></label>{tag && <button className="text-link" onClick={() => filter('etiqueta', '')}>Quitar etiqueta {tag} ×</button>}<div className="collection-count">{list.length} {list.length === 1 ? 'serie' : 'series'}</div>{list.length ? <div className="work-grid">{list.map(a => <Card key={a.id} album={a} saved={saved.includes(a.id)} onSave={onSave} />)}</div> : <div className="empty-collection"><h2>{mode === 'mine' ? 'Tu primera serie empieza acá.' : 'No hay series para mostrar.'}</h2><p>{mode === 'mine' ? 'Elegí tus imágenes y creá un álbum.' : 'Probá otra búsqueda o guardá una serie del archivo.'}</p><Link className="text-link" to={mode === 'mine' ? '/crear' : '/'}>{mode === 'mine' ? 'Crear una serie' : 'Volver al archivo'} <FaArrowRight /></Link></div>}</>;
}

function PhotoDialog({ photo, onClose }) {
  const ref = useRef(null);
  useEffect(() => { const dialog = ref.current; dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog ref={ref} className="photo-dialog" onClose={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }} aria-label={photo.title}><button className="dialog-close" onClick={onClose} aria-label="Cerrar foto"><FaTimes /></button><Image src={photo.src} alt={photo.title} /><p>{photo.title}</p></dialog>;
}

function Detail({ albums, saved, onSave, onDelete }) {
  const { id } = useParams(); const navigate = useNavigate(); const album = albums.find(a => a.id === id);
  const [photo, setPhoto] = useState(null); const [message, setMessage] = useState('');
  if (!album) return <NotFound />;
  async function share() { try { if (album.local) { setMessage('Esta serie está guardada solo en este navegador. Podremos compartirla al conectar el servidor.'); return; } await navigator.clipboard.writeText(window.location.href); setMessage('Enlace copiado. Quien lo abra necesitará entrar al acceso de prueba.'); } catch { setMessage('No se pudo copiar el enlace. Podés copiar la dirección de la barra del navegador.'); } }
  return <><Link className="back-link" to={album.local ? '/mis-albumes' : '/'}><FaArrowLeft /> Volver al archivo</Link><header className="detail-heading"><div><span className="kicker">{album.discipline} / {album.location || 'Sin ubicación'}</span><h1>{album.title}</h1><Link className="author-link" to={`/autor/${encodeURIComponent(album.author)}`}>Por {album.author}</Link></div><div className="detail-actions"><button className="outline-button" onClick={() => onSave(id)} aria-pressed={saved.includes(id)}><FaHeart /> {saved.includes(id) ? 'Guardado' : 'Guardar'}</button><button className="outline-button" onClick={share}><FaShareAlt /> Compartir</button></div></header><p className="detail-description">{album.description}</p><div className="detail-tags">{album.tags.map(t => <Link key={t} to={`/?etiqueta=${encodeURIComponent(t)}`}>#{t}</Link>)}<span>{album.photos.length} imágenes · {album.visibility === 'private' ? 'Archivo local privado' : 'Serie pública de ejemplo'}</span></div><p className="status-message" role="status">{message}</p><div className="detail-grid">{album.photos.map(p => <figure key={p.id}><button className="photo-open" onClick={() => setPhoto(p)} aria-label={`Abrir ${p.title}`}><Image src={p.src} alt={p.title} /></button><figcaption>{p.title}{album.local && <a href={p.src} download={`${p.title || 'foto'}.jpg`} aria-label={`Descargar ${p.title}`}><FaDownload /></a>}</figcaption></figure>)}</div>{album.local && <button className="delete-button" onClick={() => { if (window.confirm('¿Eliminar esta serie y sus imágenes de este navegador?')) { onDelete(id); navigate('/mis-albumes'); } }}>Eliminar mi serie</button>}{photo && <PhotoDialog photo={photo} onClose={() => setPhoto(null)} />}</>;
}

async function prepareImage(file) {
  if (!['image/jpeg','image/png','image/webp'].includes(file.type)) throw new Error('Usá imágenes JPG, PNG o WebP.');
  if (file.size > 15 * 1024 * 1024) throw new Error('Cada imagen debe pesar menos de 15 MB.');
  const bitmap = await createImageBitmap(file);
  const scale = Math.min(1, 1200 / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement('canvas'); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale);
  canvas.getContext('2d').drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
  return { id: crypto.randomUUID(), title: file.name.replace(/\.[^.]+$/, ''), src: canvas.toDataURL('image/jpeg', .76) };
}

function Create({ user, onCreate }) {
  const navigate = useNavigate(); const [photos, setPhotos] = useState([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function select(event) { const files = [...event.target.files]; setBusy(true); setError(''); try { if (photos.length + files.length > 12) throw new Error('Podés cargar hasta 12 imágenes por serie en esta versión local.'); const next = await Promise.all(files.map(prepareImage)); setPhotos(prev => [...prev, ...next]); } catch (e) { setError(e.message); } finally { setBusy(false); event.target.value = ''; } }
  function submit(event) { event.preventDefault(); if (!photos.length) { setError('Agregá al menos una imagen.'); return; } const form = new FormData(event.currentTarget); const album = { id: crypto.randomUUID(), title: form.get('title').trim(), description: form.get('description').trim(), discipline: form.get('discipline'), visibility: 'private', author: user.name || user.email.split('@')[0], location: form.get('location').trim(), tags: [...new Set(form.get('tags').split(',').map(t => t.trim()).filter(Boolean))], photos, cover: photos[0].src, date: new Date().toISOString().slice(0,10), local: true }; if (!album.title) { setError('Escribí un título.'); return; } try { onCreate(album); navigate(`/album/${album.id}`); } catch { setError('No hay espacio suficiente en este navegador. Quitá imágenes o eliminá una serie anterior.'); } }
  return <><section className="page-intro"><span className="kicker">TU ESTUDIO</span><h1>Una serie nueva.</h1><p>Seleccioná imágenes que dialoguen entre sí. La primera será tu portada.</p></section><form className="studio-form" onSubmit={submit}><label>Título<input name="title" required maxLength={100} placeholder="El nombre de tu serie" /></label><label>Descripción<textarea name="description" maxLength={1500} rows={4} placeholder="¿Qué querías contar con estas imágenes?" /></label><div className="form-columns"><label>Disciplina<select name="discipline">{disciplines.slice(1).map(d => <option key={d}>{d}</option>)}</select></label><label>Ubicación<input name="location" maxLength={100} placeholder="Ciudad, región o estudio" /></label></div><label>Etiquetas<input name="tags" maxLength={200} placeholder="Luz natural, Montaña, Retrato" /></label><label className="upload-area"><FaPlus /><strong>{busy ? 'Preparando imágenes…' : 'Elegir imágenes'}</strong><span>JPG, PNG o WebP · hasta 12 imágenes</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={select} disabled={busy} /></label><div className="upload-preview">{photos.map((p,i) => <div key={p.id}><img src={p.src} alt={p.title} /><span>{i === 0 ? 'Portada' : p.title}</span><button type="button" onClick={() => setPhotos(prev => prev.filter(item => item.id !== p.id))} aria-label={`Quitar ${p.title}`}><FaTimes /></button></div>)}</div><p className="local-note">Se guarda en este navegador, como archivo privado. Para publicar o invitar personas conectaremos el servidor. Se guardan copias optimizadas, no los originales.</p>{error && <p role="alert" className="form-error">{error}</p>}<button className="solid-button" disabled={busy} type="submit">Guardar serie <FaArrowRight /></button></form></>;
}

function Author({ albums, user }) { const { name } = useParams(); const author = name || user.name || user.email.split('@')[0]; const works = albums.filter(a => a.author === author); return <><section className="artist-heading"><span className="artist-monogram">{author[0]}</span><span className="kicker">PORTFOLIO</span><h1>{author}</h1><p>{works.length} {works.length === 1 ? 'serie' : 'series'} en el archivo</p></section><div className="portfolio-grid">{works.map(a => <Link key={a.id} to={`/album/${a.id}`}><Image src={a.cover} alt={a.title} /><h2>{a.title}</h2><span>{a.discipline}</span></Link>)}</div>{!works.length && <Link className="solid-button" to="/crear">Crear mi primera serie</Link>}</>; }
function NotFound() { return <div className="page-intro"><span className="kicker">404</span><h1>Esta página no está en el archivo.</h1><Link className="text-link" to="/">Volver al inicio <FaArrowRight /></Link></div>; }

export default function Studio({ user, setUser }) {
  const location = useLocation();
  const scope = encodeURIComponent(user.email.toLowerCase()); const key = `nexo:studio:${scope}`; const savedKey = `nexo:saved:${scope}`;
  const [localAlbums, setLocalAlbums] = useState(() => read(key, [])); const [saved, setSaved] = useState(() => read(savedKey, [])); const [notice, setNotice] = useState('');
  const albums = [...localAlbums, ...collections];
  function save(id) { const next = saved.includes(id) ? saved.filter(v => v !== id) : [...saved, id]; try { localStorage.setItem(savedKey, JSON.stringify(next)); setSaved(next); } catch { setNotice('No se pudo guardar el favorito en este navegador.'); } }
  function create(album) { const next = [album, ...localAlbums]; localStorage.setItem(key, JSON.stringify(next)); setLocalAlbums(next); }
  function remove(id) { try { const next = localAlbums.filter(a => a.id !== id); localStorage.setItem(key, JSON.stringify(next)); setLocalAlbums(next); } catch { setNotice('No se pudo eliminar la serie.'); } }
  return <div className="studio-shell"><a className="skip-link" href="#studio-main">Saltar al contenido</a><header className="studio-header"><Link className="wordmark" to="/">nexo<span>estudio</span></Link><nav aria-label="Navegación principal"><NavLink to="/" end>Descubrir</NavLink><NavLink to="/mis-albumes">Mi archivo</NavLink><NavLink to="/favoritos">Guardados</NavLink><NavLink to="/perfil">Mi perfil</NavLink></nav><Link className="header-create" to="/crear"><FaPlus /><span>Nueva serie</span></Link><button className="logout-button" onClick={() => setUser(null)} aria-label="Cerrar sesión"><FaSignOutAlt /></button></header><main id="studio-main" className="studio-main"><p role="status" className="status-message">{notice}</p><Routes><Route path="/" element={<CollectionPage albums={albums} saved={saved} onSave={save} />} /><Route path="/explorar" element={<CollectionPage albums={albums} saved={saved} onSave={save} />} /><Route path="/mis-albumes" element={<CollectionPage albums={albums} saved={saved} onSave={save} mode="mine" />} /><Route path="/favoritos" element={<CollectionPage albums={albums} saved={saved} onSave={save} mode="saved" />} /><Route path="/crear" element={<Create user={user} onCreate={create} />} /><Route path="/album/:id" element={<Detail key={location.pathname} albums={albums} saved={saved} onSave={save} onDelete={remove} />} /><Route path="/autor/:name" element={<Author albums={albums} user={user} />} /><Route path="/perfil" element={<Author albums={albums} user={user} />} /><Route path="*" element={<NotFound />} /></Routes></main><footer className="studio-footer"><span>nexo — fotografía & arte visual</span><span>Archivo de ejemplo · acceso y almacenamiento locales</span></footer></div>;
}
