import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { FaArrowLeft, FaHeart, FaShareAlt, FaDownload } from 'react-icons/fa';
import Image from '../components/Image';
import PhotoDialog from '../components/PhotoDialog';
import NotFound from './NotFound';
export default function Detail({ albums, saved, onSave, onDelete }) {
  const { id } = useParams(); const navigate = useNavigate(); const album = albums.find(a => a.id === id);
  const [photo, setPhoto] = useState(null); const [message, setMessage] = useState('');
  if (!album) return <NotFound />;
  async function share() { try { if (album.local) { setMessage('Esta serie está guardada solo en este navegador. Podremos compartirla al conectar el servidor.'); return; } await navigator.clipboard.writeText(window.location.href); setMessage('Enlace copiado. Quien lo abra necesitará entrar al acceso de prueba.'); } catch { setMessage('No se pudo copiar el enlace. Podés copiar la dirección de la barra del navegador.'); } }
  return <><Link className="back-link" to={album.local ? '/mis-albumes' : '/'}><FaArrowLeft /> Volver al archivo</Link><header className="detail-heading"><div><span className="kicker">{album.discipline} / {album.location || 'Sin ubicación'}</span><h1>{album.title}</h1><Link className="author-link" to={album.local ? "/perfil" : `/autor/${encodeURIComponent(album.author)}`}>Por {album.author}</Link></div><div className="detail-actions">{album.local && <Link className="outline-button" to={`/album/${id}/editar`}>Editar serie</Link>}<button className="outline-button" onClick={() => onSave(id)} aria-pressed={saved.includes(id)}><FaHeart /> {saved.includes(id) ? 'Guardado' : 'Guardar'}</button><button className="outline-button" onClick={share}><FaShareAlt /> Compartir</button></div></header><p className="detail-description">{album.description}</p><div className="detail-tags">{album.tags.map(t => <Link key={t} to={`/?etiqueta=${encodeURIComponent(t)}`}>#{t}</Link>)}<span>{album.photos.length} imágenes · {album.visibility === 'private' ? 'Archivo local privado' : 'Serie pública de ejemplo'}</span></div><p className="status-message" role="status">{message}</p><div className="detail-grid">{album.photos.map(p => <figure key={p.id}><button className="photo-open" onClick={() => setPhoto(p)} aria-label={`Abrir ${p.title}`}><Image src={p.src} alt={p.title} /></button><figcaption>{p.title}{album.local && <a href={p.src} download={`${p.title || 'foto'}.jpg`} aria-label={`Descargar ${p.title}`}><FaDownload /></a>}</figcaption></figure>)}</div>{album.local && <button className="delete-button" onClick={() => { if (window.confirm('¿Eliminar esta serie y sus imágenes de este navegador?')) { if (onDelete(id)) navigate('/mis-albumes'); } }}>Eliminar mi serie</button>}{photo && <PhotoDialog photo={photo} onClose={() => setPhoto(null)} />}</>;
}
