import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { FaArrowLeft, FaHeart, FaShareAlt, FaDownload } from 'react-icons/fa';
import ShareDialog from '../components/ShareDialog';
import Photo from '../components/Photo';
import { downloadPhoto } from '../../lib/backup';
import PhotoDialog from '../components/PhotoDialog';
import NotFound from './NotFound';
export default function Detail({ albums, saved, onSave, onDelete, user }) {
  const params = useParams(); const id = params.id || params.albumId; const navigate = useNavigate(); const album = albums.find(a => a.id === id);
  const [sharing,setSharing]=useState(false);
  const [photo, setPhoto] = useState(null); const [message, setMessage] = useState(''); const [deleting,setDeleting]=useState(false);
  if (!album) return deleting ? <p role="status">Eliminando serie…</p> : <NotFound />;
  async function share() { try { if (album.owned) { setSharing(true); return; } await navigator.clipboard.writeText(window.location.href); setMessage('Enlace copiado. Quien lo abra necesitará iniciar sesión.'); } catch { setMessage('No se pudo copiar el enlace. Podés copiar la dirección de la barra del navegador.'); } }
  return <><Link className="back-link" to={album.owned ? '/mis-albumes' : album.shared ? '/compartidos' : '/'}><FaArrowLeft /> Volver al archivo</Link><header className="detail-heading"><div><span className="kicker">{album.discipline} / {album.location || 'Sin ubicación'}</span><h1>{album.title}</h1>{album.shared ? <span className="author-link">Álbum compartido · solo lectura</span> : <Link className="author-link" to={album.owned ? "/perfil" : `/autor/${encodeURIComponent(album.author)}`}>Por {album.author}</Link>}</div><div className="detail-actions">{album.owned && <Link className="outline-button" to={`/album/${id}/editar`}>Editar serie</Link>}{!album.shared && <button className="outline-button" onClick={() => onSave(id)} aria-pressed={saved.includes(id)}><FaHeart /> {saved.includes(id) ? 'Guardado' : 'Guardar'}</button>} {!album.shared && <button className="outline-button" onClick={share}><FaShareAlt /> Compartir</button>}</div></header><p className="detail-description">{album.description}</p><div className="detail-tags">{album.tags.map(t => <Link key={t} to={`${album.owned ? "/mis-albumes" : "/"}?etiqueta=${encodeURIComponent(t)}`}>#{t}</Link>)}<span>{album.photos.length} imágenes · {album.visibility === 'private' ? 'Archivo privado en Firebase' : 'Serie pública de ejemplo'}</span></div><p className="status-message" role="status">{message}</p><div className="detail-grid">{album.photos.map(p => <figure key={p.id}><button className="photo-open" onClick={() => setPhoto(p)} aria-label={`Abrir ${p.title}`}><Photo photo={p} alt={p.title} /></button><figcaption><span>{p.title}{p.credit && <a className="photo-credit" href={p.source} target="_blank" rel="noreferrer">Foto: {p.credit} / Unsplash ↗</a>}</span>{album.owned && <button className="text-link" onClick={async () => { try { await downloadPhoto(p); } catch { setMessage("No se pudo descargar la foto. Revisá conexión y permisos."); } }} aria-label={`Descargar ${p.title}`}><FaDownload /></button>}</figcaption></figure>)}</div>{album.owned && <button className="delete-button" disabled={deleting} onClick={async () => { if (window.confirm('¿Eliminar esta serie y sus imágenes de Firebase?')) { setDeleting(true); if (await onDelete(id)) navigate('/mis-albumes'); else setDeleting(false); } }}>Eliminar mi serie</button>}{sharing && <ShareDialog album={album} user={user} onClose={()=>setSharing(false)} />}{photo && <PhotoDialog photo={photo} onClose={() => setPhoto(null)} />}</>;
}
