import { Link, useParams } from 'react-router-dom';
import PageIntro from '../components/PageIntro';
import NotFound from './NotFound';
const lessons = [
  { id: 'luz', title: 'Leer la luz', category: 'LUZ / 01', intro: 'Antes de ajustar la cámara, mirá de dónde viene la luz.', paragraphs: ['La luz lateral muestra textura y volumen. La luz frontal reduce sombras; el contraluz puede separar la silueta del fondo. Probá los tres ángulos con el mismo sujeto.', 'Si la luz del mediodía te resulta dura, buscá sombra abierta junto a una ventana o un edificio. Una cortina clara puede suavizar la luz de una ventana.'], exercise: 'Fotografiá un objeto junto a una ventana desde tres posiciones. Compará las sombras y elegí la imagen que mejor cuenta su forma.' },
  { id: 'composicion', title: 'Elegir qué dejar afuera', category: 'COMPOSICIÓN / 02', intro: 'Una foto empieza en el encuadre y en las decisiones que tomás.', paragraphs: ['Recorré los bordes antes de disparar. Un elemento cortado o muy brillante puede distraer del protagonista. Movete unos pasos antes de recurrir al zoom.', 'Las líneas, el espacio vacío y las repeticiones pueden guiar la mirada. La regla de tercios es una posibilidad: también podés usar simetría o un encuadre centrado cuando ayuden a tu intención.'], exercise: 'Hacé cinco encuadres del mismo lugar sin cambiar de lente. Buscá una versión donde cada elemento tenga una razón para estar.' },
  { id: 'serie', title: 'Construir una serie', category: 'EDICIÓN / 03', intro: 'Una serie puede contar algo que una imagen sola deja abierto.', paragraphs: ['Elegí una intención y reducí la selección. Alterná planos generales, detalles y pausas para darle un ritmo. Dos imágenes muy parecidas pueden competir: probá conservar una sola.', 'Revisá la secuencia completa y elegí una portada que abra una pregunta. Escribí una descripción breve que aporte contexto sin explicar cada foto.'], exercise: 'Seleccioná seis imágenes de una salida. Ordenalas de dos maneras distintas y contá qué cambia en la historia.' },
];
export default function Learn() {
  const { id } = useParams(); const lesson = lessons.find(item => item.id === id);
  if (id && !lesson) return <NotFound />;
  if (lesson) return <article className="lesson"><Link className="back-link" to="/aprender">← Todas las guías</Link><PageIntro eyebrow={lesson.category} title={lesson.title}>{lesson.intro}</PageIntro>{lesson.paragraphs.map(p => <p key={p}>{p}</p>)}<aside className="info-panel"><h2>Para practicar</h2><p>{lesson.exercise}</p><Link className="text-link" to="/crear">Crear una serie con el ejercicio →</Link></aside></article>;
  return <><PageIntro eyebrow="CUADERNO DE ESTUDIO" title="Entrená tu mirada.">Guías breves y ejercicios para explorar la luz, el encuadre y la edición. Contenido fijo, sin análisis automático de tus fotos.</PageIntro><div className="lesson-grid">{lessons.map(item => <Link className="info-panel lesson-card" key={item.id} to={`/aprender/${item.id}`}><span className="kicker">{item.category}</span><h2>{item.title}</h2><p>{item.intro}</p><span className="text-link">Leer y practicar →</span></Link>)}</div></>;
}
