import { useEffect, useRef, useState } from 'react';
import { cloudError } from '../../lib/cloudArchive';
import { inviteToAlbum, revokeInvitation, watchInvitations } from '../../lib/sharing';
export default function ShareDialog({ album, user, onClose }) {
  const dialog = useRef(null); const [email,setEmail] = useState(''); const [people,setPeople] = useState([]);
  const [busy,setBusy] = useState(false); const [message,setMessage] = useState(''); const [loading,setLoading] = useState(true);
  useEffect(()=>{const node=dialog.current;if(!node.open)node.showModal();},[]);
  useEffect(()=>watchInvitations(user.uid,album.id,list=>{setPeople(list);setLoading(false);},err=>{setMessage(cloudError(err));setLoading(false);}),[user.uid,album.id]);
  async function invite(event) { event.preventDefault();setBusy(true);try { await inviteToAlbum(user.uid,album.id,email);setEmail('');setMessage('Invitación creada. La persona la verá en Compartidos conmigo al verificar su correo.'); } catch(err) {setMessage(cloudError(err));}finally {setBusy(false);} }
  return <dialog ref={dialog} className="share-dialog" aria-labelledby="share-title" onClose={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}}><button className="dialog-close" onClick={onClose} aria-label="Cerrar invitaciones">×</button><span className="kicker">ACCESO POR INVITACIÓN</span><h2 id="share-title">Compartir {album.title}</h2><p>Invitá a alguien por su correo. Podrá ver las fotos, sin modificar tu serie. La invitación aparece en Nexo; no se envía un correo automático. Quitar el acceso impide nuevas lecturas, pero no borra copias que la persona ya haya conservado.</p><form onSubmit={invite}><label htmlFor="invite-email">Correo de la persona</label><input id="invite-email" type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="persona@correo.com" /><button className="solid-button" disabled={busy || loading}>{busy?'Creando invitación…':'Invitar a ver'}</button></form><p role="status">{message}</p><h3>Personas con acceso</h3>{loading?<p role="status">Cargando invitaciones…</p>:people.length?<ul>{people.map(person=><li key={person.id}><div><strong>{person.recipientEmail}</strong><span>Solo lectura · correo verificado</span></div><button className="text-link" disabled={busy} onClick={async()=>{setBusy(true);try{await revokeInvitation(user.uid,album.id,person.id);setMessage('Acceso revocado.');}catch(err){setMessage(cloudError(err));}finally{setBusy(false);}}}>Quitar acceso</button></li>)}</ul>:<p>Solo vos tenés acceso a este álbum.</p>}</dialog>;
}
